FROM python:3.13.11-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/


# RUN pip install pyarrow pandas
WORKDIR /code
ENV PATH="/code/.venv/bin:$PATH"

COPY pipeline.py ./
COPY pyproject.toml .python-version uv.lock ./
RUN uv sync --locked

# ENTRYPOINT ["python", "pipeline.py"]